# -*- coding: utf-8 -*-
"""MetaStaaq.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1j-biqiWJFiN_FN7YIBsOLeiW2uEVeQ0T

Refactored version - now uses modular functions from separate files.
"""

import pandas as pd

# Import only the simulation runner - it handles all the individual functions internally
from run_simulation import run_simulation

# Load data - update path as needed
# data_content = pd.read_csv('/content/drive/MyDrive/STAAQ/METASTAAQ/donnees_prix_spot_processed_2020_2025.csv')
data_content = pd.read_csv('processed_donnees_prix_spot_fr_2021_2025_month_8.csv')

years_subset = [2024, 2025]
data_content = data_content[data_content['Annee'].isin(years_subset)]

electrolyser_power = 5 # MW
electrolyser_specific_consumption = 4.8 # kWh/Nm3 H2
h2_flowrate = round((electrolyser_power * 1000)/electrolyser_specific_consumption) # Nm3/h
stoechio_H2_CH4 = 4
ch4_flowrate = round(h2_flowrate / stoechio_H2_CH4) # Nm3/h
ch4_density = 0.7168  # kg/Nm³ CH₄
ch4_kg_per_day = ch4_flowrate * 24 * ch4_density  # kg/day

#target_prices = [5,10,15,20,25,30,35,40] # €/MwH
target_prices = [15]
service_ratio = 0.98 # 0->1

# All function definitions have been moved to separate files

"""# Tables and Charts"""

for target_price in target_prices:
    run_simulation(data_content, target_price, service_ratio, electrolyser_power, ch4_kg_per_day)
    print("--------------------------------------------------------------------------------------------------------------------------------------")